name: CI

on:
  push:
    branches:
      - ttt

  pull_request:
    branches:
      - ttt
      - tt

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    if: github.event_name != 'pull_request' || github.base_ref != 'master' || github.head_ref != 'refs/heads/develop'

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: âš™ï¸ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: ğŸ“¥ Install dependencies
        run: bun install --frozen-lockfile

      - name: ğŸ“ Run type checking for all packages
        run: bun run type-check

      - name: ğŸ§¹ Run linting for all packages
        run: bun run lint

      - name: ğŸ› ï¸ Build all projects
        run: bun run build

      - name: ğŸ§ª Run tests for all packages
        run: bun run test

      - name: â˜‚ï¸ Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/devkit
          json-summary-path: "./coverage/coverage-summary.json"
          json-final-path: "./coverage/coverage-final.json"
