name: CI

on:
  push:
    branches:
      - develop


  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reusable Setup
        uses: ./.github/actions/setup
      - name: Reusable Setup
        uses: ./.github/actions/setup
        with:
          bun_version: "latest"

      - name: ğŸ“ Run type checking for all packages
        run: bun run type-check

      - name: ğŸ§¹ Run linting for all packages
        run: bun run lint

      - name: ğŸ› ï¸ Build all projects
        run: bun run build

      - name: ğŸ§ª Run tests for all packages
        run: bun run test

      - name: â˜‚ï¸ Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/devkit
          json-summary-path: "./coverage/coverage-summary.json"
          json-final-path: "./coverage/coverage-final.json"
